### ISSUE TITLE
Missing action in the form

### ISSUE THREAD

**Issue by TodorovStanimir** [teodortenchev/CatShelter#1]
https://github.com/teodortenchev/CatShelter/blob/c5637a6f5b31e015a8947f70e837a2967b429e40/views/addCat.html#L22

**Comment by TodorovStanimir** [comment]
Have to add - action="/cats/add-cat"

**Comment by teodortenchev** [comment]
Hello,thanks for pointing this out. I've fixed it. There was also another issue in the handler which is now fixed thanks to this remark.
